// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC19bzrZZC739UOxthzwnYyp-0Q5w52k_A',
    appId: '1:944058482972:web:1385cc6d26af6c3e7a7ad9',
    messagingSenderId: '944058482972',
    projectId: 'chatter-74e27',
    authDomain: 'chatter-74e27.firebaseapp.com',
    storageBucket: 'chatter-74e27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1r_yLUGkUJfRrOc2-2D-lwoRbwBskB0A',
    appId: '1:944058482972:android:04d9ccf06e31f1967a7ad9',
    messagingSenderId: '944058482972',
    projectId: 'chatter-74e27',
    storageBucket: 'chatter-74e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtruStff-Gs690tJh6JJ2PVxQQvqcYlxg',
    appId: '1:944058482972:ios:b1641be392e7600b7a7ad9',
    messagingSenderId: '944058482972',
    projectId: 'chatter-74e27',
    storageBucket: 'chatter-74e27.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtruStff-Gs690tJh6JJ2PVxQQvqcYlxg',
    appId: '1:944058482972:ios:7350bf21a5b07e9d7a7ad9',
    messagingSenderId: '944058482972',
    projectId: 'chatter-74e27',
    storageBucket: 'chatter-74e27.appspot.com',
    iosBundleId: 'com.example.chatter.RunnerTests',
  );
}
